# version of the docker-compose
version: "3"
services:
# list of containers
  mongodb:
    image: mongo
    ports:
    # host:container
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mahya
      - MONGO_INITDB_ROOT_PASSWORD=123456
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mahya
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb